(define
 (problem pfile_005)
 (:domain blocks)
 (:objects b1 b2 b3 b4 b5 - BLOCK)
 (:init
  (hand-empty)
  (clear b3)
  (on-table b2)
  (on b3 b5)
  (on b5 b4)
  (on b4 b2)
  (clear b1)
  (on-table b1))
 (:goal (and
         (clear b2)
         (on-table b4)
         (on b2 b5)
         (on b5 b4)
         (clear b1)
         (on-table b3)
         (on b1 b3)))
    (:tasks (task0 (achieve-goals)))
         )