(defproblem problem domain 
  (
    (visible waypoint1 waypoint0)
    (visible waypoint0 waypoint1)
    (visible waypoint2 waypoint0)
    (visible waypoint0 waypoint2)
    (visible waypoint2 waypoint1)
    (visible waypoint1 waypoint2)
    (visible waypoint3 waypoint0)
    (visible waypoint0 waypoint3)
    (visible waypoint3 waypoint1)
    (visible waypoint1 waypoint3)
    (visible waypoint3 waypoint2)
    (visible waypoint2 waypoint3)
    (at_soil_sample waypoint0)
    (at_rock_sample waypoint1)
    (at_soil_sample waypoint2)
    (at_rock_sample waypoint2)
    (at_soil_sample waypoint3)
    (at_rock_sample waypoint3)
    (at_lander general waypoint0)
    (channel_free general)
    (at rover0 waypoint3)
    (available rover0)
    (store_of rover0store rover0)
    (empty rover0store)
    (equipped_for_soil_analysis rover0)
    (equipped_for_rock_analysis rover0)
    (equipped_for_imaging rover0)
    (can_traverse rover0 waypoint3 waypoint0)
    (can_traverse rover0 waypoint0 waypoint3)
    (can_traverse rover0 waypoint3 waypoint1)
    (can_traverse rover0 waypoint1 waypoint3)
    (can_traverse rover0 waypoint1 waypoint2)
    (can_traverse rover0 waypoint2 waypoint1)
    (on_board camera0 rover0)
    (calibration_target camera0 objective1)
    (supports camera0 colour)
    (supports camera0 high_res)
    (visible_from objective0 waypoint0)
    (visible_from objective0 waypoint1)
    (visible_from objective0 waypoint2)
    (visible_from objective0 waypoint3)
    (visible_from objective1 waypoint0)
    (visible_from objective1 waypoint1)
    (visible_from objective1 waypoint2)
    (visible_from objective1 waypoint3)
    (type_camera camera0)
    (type_lander general)
    (type_mode colour)
    (type_mode high_res)
    (type_mode low_res)
    (type_object camera0)
    (type_object colour)
    (type_object general)
    (type_object high_res)
    (type_object low_res)
    (type_object objective0)
    (type_object objective1)
    (type_object rover0)
    (type_object rover0store)
    (type_object waypoint0)
    (type_object waypoint1)
    (type_object waypoint2)
    (type_object waypoint3)
    (type_objective objective0)
    (type_objective objective1)
    (type_rover rover0)
    (type_sort_for_camera0 camera0)
    (type_sort_for_colour colour)
    (type_sort_for_general general)
    (type_sort_for_high_res high_res)
    (type_sort_for_objective0 objective0)
    (type_sort_for_objective1 objective1)
    (type_sort_for_rover0 rover0)
    (type_sort_for_rover0store rover0store)
    (type_sort_for_waypoint0 waypoint0)
    (type_sort_for_waypoint1 waypoint1)
    (type_sort_for_waypoint2 waypoint2)
    (type_sort_for_waypoint3 waypoint3)
    (type_store rover0store)
    (type_waypoint waypoint0)
    (type_waypoint waypoint1)
    (type_waypoint waypoint2)
    (type_waypoint waypoint3)
  )
  ((__top))
)
