(defproblem problem domain 
  (
    (visible waypoint0 waypoint1)
    (visible waypoint1 waypoint0)
    (visible waypoint0 waypoint3)
    (visible waypoint3 waypoint0)
    (visible waypoint1 waypoint5)
    (visible waypoint5 waypoint1)
    (visible waypoint2 waypoint0)
    (visible waypoint0 waypoint2)
    (visible waypoint2 waypoint1)
    (visible waypoint1 waypoint2)
    (visible waypoint2 waypoint3)
    (visible waypoint3 waypoint2)
    (visible waypoint2 waypoint4)
    (visible waypoint4 waypoint2)
    (visible waypoint3 waypoint4)
    (visible waypoint4 waypoint3)
    (visible waypoint3 waypoint5)
    (visible waypoint5 waypoint3)
    (visible waypoint4 waypoint0)
    (visible waypoint0 waypoint4)
    (visible waypoint4 waypoint1)
    (visible waypoint1 waypoint4)
    (visible waypoint5 waypoint2)
    (visible waypoint2 waypoint5)
    (visible waypoint5 waypoint4)
    (visible waypoint4 waypoint5)
    (at_soil_sample waypoint1)
    (at_rock_sample waypoint2)
    (at_soil_sample waypoint3)
    (at_rock_sample waypoint3)
    (at_soil_sample waypoint4)
    (at_rock_sample waypoint4)
    (at_rock_sample waypoint5)
    (at_lander general waypoint0)
    (channel_free general)
    (at rover0 waypoint2)
    (available rover0)
    (store_of rover0store rover0)
    (empty rover0store)
    (equipped_for_soil_analysis rover0)
    (equipped_for_rock_analysis rover0)
    (can_traverse rover0 waypoint2 waypoint0)
    (can_traverse rover0 waypoint0 waypoint2)
    (can_traverse rover0 waypoint2 waypoint3)
    (can_traverse rover0 waypoint3 waypoint2)
    (can_traverse rover0 waypoint2 waypoint4)
    (can_traverse rover0 waypoint4 waypoint2)
    (can_traverse rover0 waypoint0 waypoint1)
    (can_traverse rover0 waypoint1 waypoint0)
    (can_traverse rover0 waypoint3 waypoint5)
    (can_traverse rover0 waypoint5 waypoint3)
    (at rover1 waypoint2)
    (available rover1)
    (store_of rover1store rover1)
    (empty rover1store)
    (equipped_for_rock_analysis rover1)
    (equipped_for_imaging rover1)
    (can_traverse rover1 waypoint2 waypoint0)
    (can_traverse rover1 waypoint0 waypoint2)
    (can_traverse rover1 waypoint2 waypoint3)
    (can_traverse rover1 waypoint3 waypoint2)
    (can_traverse rover1 waypoint2 waypoint5)
    (can_traverse rover1 waypoint5 waypoint2)
    (can_traverse rover1 waypoint0 waypoint1)
    (can_traverse rover1 waypoint1 waypoint0)
    (can_traverse rover1 waypoint3 waypoint4)
    (can_traverse rover1 waypoint4 waypoint3)
    (at rover2 waypoint2)
    (available rover2)
    (store_of rover2store rover2)
    (empty rover2store)
    (equipped_for_rock_analysis rover2)
    (equipped_for_imaging rover2)
    (can_traverse rover2 waypoint2 waypoint0)
    (can_traverse rover2 waypoint0 waypoint2)
    (can_traverse rover2 waypoint2 waypoint1)
    (can_traverse rover2 waypoint1 waypoint2)
    (can_traverse rover2 waypoint2 waypoint4)
    (can_traverse rover2 waypoint4 waypoint2)
    (can_traverse rover2 waypoint2 waypoint5)
    (can_traverse rover2 waypoint5 waypoint2)
    (can_traverse rover2 waypoint0 waypoint3)
    (can_traverse rover2 waypoint3 waypoint0)
    (at rover3 waypoint3)
    (available rover3)
    (store_of rover3store rover3)
    (empty rover3store)
    (equipped_for_soil_analysis rover3)
    (equipped_for_rock_analysis rover3)
    (equipped_for_imaging rover3)
    (can_traverse rover3 waypoint3 waypoint0)
    (can_traverse rover3 waypoint0 waypoint3)
    (can_traverse rover3 waypoint3 waypoint2)
    (can_traverse rover3 waypoint2 waypoint3)
    (can_traverse rover3 waypoint3 waypoint4)
    (can_traverse rover3 waypoint4 waypoint3)
    (can_traverse rover3 waypoint0 waypoint1)
    (can_traverse rover3 waypoint1 waypoint0)
    (can_traverse rover3 waypoint2 waypoint5)
    (can_traverse rover3 waypoint5 waypoint2)
    (on_board camera0 rover3)
    (calibration_target camera0 objective1)
    (supports camera0 colour)
    (supports camera0 high_res)
    (supports camera0 low_res)
    (on_board camera1 rover3)
    (calibration_target camera1 objective0)
    (supports camera1 colour)
    (supports camera1 high_res)
    (on_board camera2 rover1)
    (calibration_target camera2 objective0)
    (supports camera2 colour)
    (supports camera2 high_res)
    (supports camera2 low_res)
    (on_board camera3 rover2)
    (calibration_target camera3 objective1)
    (supports camera3 colour)
    (supports camera3 low_res)
    (visible_from objective0 waypoint0)
    (visible_from objective0 waypoint1)
    (visible_from objective0 waypoint2)
    (visible_from objective1 waypoint0)
    (visible_from objective2 waypoint0)
    (visible_from objective2 waypoint1)
    (visible_from objective2 waypoint2)
    (type_camera camera0)
    (type_camera camera1)
    (type_camera camera2)
    (type_camera camera3)
    (type_lander general)
    (type_mode colour)
    (type_mode high_res)
    (type_mode low_res)
    (type_object camera0)
    (type_object camera1)
    (type_object camera2)
    (type_object camera3)
    (type_object colour)
    (type_object general)
    (type_object high_res)
    (type_object low_res)
    (type_object objective0)
    (type_object objective1)
    (type_object objective2)
    (type_object rover0)
    (type_object rover0store)
    (type_object rover1)
    (type_object rover1store)
    (type_object rover2)
    (type_object rover2store)
    (type_object rover3)
    (type_object rover3store)
    (type_object waypoint0)
    (type_object waypoint1)
    (type_object waypoint2)
    (type_object waypoint3)
    (type_object waypoint4)
    (type_object waypoint5)
    (type_objective objective0)
    (type_objective objective1)
    (type_objective objective2)
    (type_rover rover0)
    (type_rover rover1)
    (type_rover rover2)
    (type_rover rover3)
    (type_sort_for_camera0 camera0)
    (type_sort_for_camera1 camera1)
    (type_sort_for_camera2 camera2)
    (type_sort_for_camera3 camera3)
    (type_sort_for_colour colour)
    (type_sort_for_general general)
    (type_sort_for_high_res high_res)
    (type_sort_for_low_res low_res)
    (type_sort_for_objective0 objective0)
    (type_sort_for_objective1 objective1)
    (type_sort_for_objective2 objective2)
    (type_sort_for_rover0 rover0)
    (type_sort_for_rover0store rover0store)
    (type_sort_for_rover1 rover1)
    (type_sort_for_rover1store rover1store)
    (type_sort_for_rover2 rover2)
    (type_sort_for_rover2store rover2store)
    (type_sort_for_rover3 rover3)
    (type_sort_for_rover3store rover3store)
    (type_sort_for_waypoint0 waypoint0)
    (type_sort_for_waypoint1 waypoint1)
    (type_sort_for_waypoint2 waypoint2)
    (type_sort_for_waypoint3 waypoint3)
    (type_sort_for_waypoint4 waypoint4)
    (type_sort_for_waypoint5 waypoint5)
    (type_store rover0store)
    (type_store rover1store)
    (type_store rover2store)
    (type_store rover3store)
    (type_waypoint waypoint0)
    (type_waypoint waypoint1)
    (type_waypoint waypoint2)
    (type_waypoint waypoint3)
    (type_waypoint waypoint4)
    (type_waypoint waypoint5)
  )
  ((__top))
)
