(defproblem problem domain 
  (
    (visible waypoint0 waypoint5)
    (visible waypoint5 waypoint0)
    (visible waypoint0 waypoint15)
    (visible waypoint15 waypoint0)
    (visible waypoint0 waypoint23)
    (visible waypoint23 waypoint0)
    (visible waypoint1 waypoint23)
    (visible waypoint23 waypoint1)
    (visible waypoint2 waypoint1)
    (visible waypoint1 waypoint2)
    (visible waypoint2 waypoint5)
    (visible waypoint5 waypoint2)
    (visible waypoint2 waypoint6)
    (visible waypoint6 waypoint2)
    (visible waypoint2 waypoint14)
    (visible waypoint14 waypoint2)
    (visible waypoint2 waypoint16)
    (visible waypoint16 waypoint2)
    (visible waypoint2 waypoint23)
    (visible waypoint23 waypoint2)
    (visible waypoint3 waypoint1)
    (visible waypoint1 waypoint3)
    (visible waypoint3 waypoint13)
    (visible waypoint13 waypoint3)
    (visible waypoint3 waypoint15)
    (visible waypoint15 waypoint3)
    (visible waypoint3 waypoint18)
    (visible waypoint18 waypoint3)
    (visible waypoint3 waypoint20)
    (visible waypoint20 waypoint3)
    (visible waypoint4 waypoint1)
    (visible waypoint1 waypoint4)
    (visible waypoint4 waypoint6)
    (visible waypoint6 waypoint4)
    (visible waypoint4 waypoint13)
    (visible waypoint13 waypoint4)
    (visible waypoint4 waypoint16)
    (visible waypoint16 waypoint4)
    (visible waypoint4 waypoint19)
    (visible waypoint19 waypoint4)
    (visible waypoint4 waypoint20)
    (visible waypoint20 waypoint4)
    (visible waypoint5 waypoint1)
    (visible waypoint1 waypoint5)
    (visible waypoint5 waypoint4)
    (visible waypoint4 waypoint5)
    (visible waypoint5 waypoint8)
    (visible waypoint8 waypoint5)
    (visible waypoint5 waypoint16)
    (visible waypoint16 waypoint5)
    (visible waypoint6 waypoint5)
    (visible waypoint5 waypoint6)
    (visible waypoint6 waypoint8)
    (visible waypoint8 waypoint6)
    (visible waypoint6 waypoint9)
    (visible waypoint9 waypoint6)
    (visible waypoint6 waypoint11)
    (visible waypoint11 waypoint6)
    (visible waypoint6 waypoint21)
    (visible waypoint21 waypoint6)
    (visible waypoint7 waypoint0)
    (visible waypoint0 waypoint7)
    (visible waypoint7 waypoint4)
    (visible waypoint4 waypoint7)
    (visible waypoint7 waypoint8)
    (visible waypoint8 waypoint7)
    (visible waypoint7 waypoint16)
    (visible waypoint16 waypoint7)
    (visible waypoint7 waypoint17)
    (visible waypoint17 waypoint7)
    (visible waypoint8 waypoint4)
    (visible waypoint4 waypoint8)
    (visible waypoint8 waypoint16)
    (visible waypoint16 waypoint8)
    (visible waypoint8 waypoint17)
    (visible waypoint17 waypoint8)
    (visible waypoint9 waypoint2)
    (visible waypoint2 waypoint9)
    (visible waypoint9 waypoint5)
    (visible waypoint5 waypoint9)
    (visible waypoint9 waypoint7)
    (visible waypoint7 waypoint9)
    (visible waypoint9 waypoint14)
    (visible waypoint14 waypoint9)
    (visible waypoint9 waypoint17)
    (visible waypoint17 waypoint9)
    (visible waypoint10 waypoint11)
    (visible waypoint11 waypoint10)
    (visible waypoint10 waypoint15)
    (visible waypoint15 waypoint10)
    (visible waypoint11 waypoint8)
    (visible waypoint8 waypoint11)
    (visible waypoint11 waypoint19)
    (visible waypoint19 waypoint11)
    (visible waypoint12 waypoint3)
    (visible waypoint3 waypoint12)
    (visible waypoint12 waypoint6)
    (visible waypoint6 waypoint12)
    (visible waypoint12 waypoint11)
    (visible waypoint11 waypoint12)
    (visible waypoint12 waypoint13)
    (visible waypoint13 waypoint12)
    (visible waypoint12 waypoint19)
    (visible waypoint19 waypoint12)
    (visible waypoint12 waypoint22)
    (visible waypoint22 waypoint12)
    (visible waypoint12 waypoint23)
    (visible waypoint23 waypoint12)
    (visible waypoint12 waypoint24)
    (visible waypoint24 waypoint12)
    (visible waypoint13 waypoint14)
    (visible waypoint14 waypoint13)
    (visible waypoint13 waypoint15)
    (visible waypoint15 waypoint13)
    (visible waypoint13 waypoint20)
    (visible waypoint20 waypoint13)
    (visible waypoint14 waypoint0)
    (visible waypoint0 waypoint14)
    (visible waypoint14 waypoint1)
    (visible waypoint1 waypoint14)
    (visible waypoint14 waypoint5)
    (visible waypoint5 waypoint14)
    (visible waypoint14 waypoint6)
    (visible waypoint6 waypoint14)
    (visible waypoint14 waypoint8)
    (visible waypoint8 waypoint14)
    (visible waypoint14 waypoint12)
    (visible waypoint12 waypoint14)
    (visible waypoint14 waypoint20)
    (visible waypoint20 waypoint14)
    (visible waypoint15 waypoint1)
    (visible waypoint1 waypoint15)
    (visible waypoint15 waypoint6)
    (visible waypoint6 waypoint15)
    (visible waypoint15 waypoint12)
    (visible waypoint12 waypoint15)
    (visible waypoint15 waypoint16)
    (visible waypoint16 waypoint15)
    (visible waypoint16 waypoint10)
    (visible waypoint10 waypoint16)
    (visible waypoint16 waypoint20)
    (visible waypoint20 waypoint16)
    (visible waypoint17 waypoint11)
    (visible waypoint11 waypoint17)
    (visible waypoint17 waypoint14)
    (visible waypoint14 waypoint17)
    (visible waypoint17 waypoint15)
    (visible waypoint15 waypoint17)
    (visible waypoint17 waypoint18)
    (visible waypoint18 waypoint17)
    (visible waypoint17 waypoint20)
    (visible waypoint20 waypoint17)
    (visible waypoint18 waypoint0)
    (visible waypoint0 waypoint18)
    (visible waypoint18 waypoint1)
    (visible waypoint1 waypoint18)
    (visible waypoint18 waypoint6)
    (visible waypoint6 waypoint18)
    (visible waypoint18 waypoint8)
    (visible waypoint8 waypoint18)
    (visible waypoint18 waypoint9)
    (visible waypoint9 waypoint18)
    (visible waypoint18 waypoint10)
    (visible waypoint10 waypoint18)
    (visible waypoint19 waypoint6)
    (visible waypoint6 waypoint19)
    (visible waypoint19 waypoint21)
    (visible waypoint21 waypoint19)
    (visible waypoint20 waypoint19)
    (visible waypoint19 waypoint20)
    (visible waypoint21 waypoint4)
    (visible waypoint4 waypoint21)
    (visible waypoint21 waypoint5)
    (visible waypoint5 waypoint21)
    (visible waypoint21 waypoint8)
    (visible waypoint8 waypoint21)
    (visible waypoint21 waypoint11)
    (visible waypoint11 waypoint21)
    (visible waypoint21 waypoint13)
    (visible waypoint13 waypoint21)
    (visible waypoint21 waypoint17)
    (visible waypoint17 waypoint21)
    (visible waypoint21 waypoint18)
    (visible waypoint18 waypoint21)
    (visible waypoint22 waypoint11)
    (visible waypoint11 waypoint22)
    (visible waypoint22 waypoint16)
    (visible waypoint16 waypoint22)
    (visible waypoint22 waypoint21)
    (visible waypoint21 waypoint22)
    (visible waypoint23 waypoint10)
    (visible waypoint10 waypoint23)
    (visible waypoint23 waypoint18)
    (visible waypoint18 waypoint23)
    (visible waypoint23 waypoint20)
    (visible waypoint20 waypoint23)
    (visible waypoint24 waypoint5)
    (visible waypoint5 waypoint24)
    (visible waypoint24 waypoint7)
    (visible waypoint7 waypoint24)
    (visible waypoint24 waypoint18)
    (visible waypoint18 waypoint24)
    (visible waypoint24 waypoint20)
    (visible waypoint20 waypoint24)
    (visible waypoint24 waypoint23)
    (visible waypoint23 waypoint24)
    (at_soil_sample waypoint0)
    (at_soil_sample waypoint1)
    (at_soil_sample waypoint7)
    (at_rock_sample waypoint7)
    (at_soil_sample waypoint8)
    (at_soil_sample waypoint9)
    (at_rock_sample waypoint9)
    (at_rock_sample waypoint10)
    (at_soil_sample waypoint11)
    (at_rock_sample waypoint12)
    (at_soil_sample waypoint13)
    (at_rock_sample waypoint14)
    (at_soil_sample waypoint15)
    (at_rock_sample waypoint16)
    (at_soil_sample waypoint17)
    (at_soil_sample waypoint18)
    (at_rock_sample waypoint18)
    (at_soil_sample waypoint20)
    (at_rock_sample waypoint21)
    (at_soil_sample waypoint22)
    (at_rock_sample waypoint22)
    (at_soil_sample waypoint23)
    (at_soil_sample waypoint24)
    (at_lander general waypoint1)
    (channel_free general)
    (at rover0 waypoint22)
    (available rover0)
    (store_of rover0store rover0)
    (empty rover0store)
    (equipped_for_soil_analysis rover0)
    (equipped_for_imaging rover0)
    (can_traverse rover0 waypoint22 waypoint11)
    (can_traverse rover0 waypoint11 waypoint22)
    (can_traverse rover0 waypoint22 waypoint12)
    (can_traverse rover0 waypoint12 waypoint22)
    (can_traverse rover0 waypoint22 waypoint21)
    (can_traverse rover0 waypoint21 waypoint22)
    (can_traverse rover0 waypoint11 waypoint6)
    (can_traverse rover0 waypoint6 waypoint11)
    (can_traverse rover0 waypoint11 waypoint8)
    (can_traverse rover0 waypoint8 waypoint11)
    (can_traverse rover0 waypoint11 waypoint10)
    (can_traverse rover0 waypoint10 waypoint11)
    (can_traverse rover0 waypoint11 waypoint17)
    (can_traverse rover0 waypoint17 waypoint11)
    (can_traverse rover0 waypoint11 waypoint19)
    (can_traverse rover0 waypoint19 waypoint11)
    (can_traverse rover0 waypoint12 waypoint13)
    (can_traverse rover0 waypoint13 waypoint12)
    (can_traverse rover0 waypoint12 waypoint15)
    (can_traverse rover0 waypoint15 waypoint12)
    (can_traverse rover0 waypoint12 waypoint24)
    (can_traverse rover0 waypoint24 waypoint12)
    (can_traverse rover0 waypoint21 waypoint4)
    (can_traverse rover0 waypoint4 waypoint21)
    (can_traverse rover0 waypoint21 waypoint5)
    (can_traverse rover0 waypoint5 waypoint21)
    (can_traverse rover0 waypoint21 waypoint18)
    (can_traverse rover0 waypoint18 waypoint21)
    (can_traverse rover0 waypoint6 waypoint2)
    (can_traverse rover0 waypoint2 waypoint6)
    (can_traverse rover0 waypoint6 waypoint9)
    (can_traverse rover0 waypoint9 waypoint6)
    (can_traverse rover0 waypoint6 waypoint14)
    (can_traverse rover0 waypoint14 waypoint6)
    (can_traverse rover0 waypoint8 waypoint7)
    (can_traverse rover0 waypoint7 waypoint8)
    (can_traverse rover0 waypoint17 waypoint20)
    (can_traverse rover0 waypoint20 waypoint17)
    (can_traverse rover0 waypoint13 waypoint3)
    (can_traverse rover0 waypoint3 waypoint13)
    (can_traverse rover0 waypoint15 waypoint1)
    (can_traverse rover0 waypoint1 waypoint15)
    (can_traverse rover0 waypoint15 waypoint16)
    (can_traverse rover0 waypoint16 waypoint15)
    (can_traverse rover0 waypoint24 waypoint23)
    (can_traverse rover0 waypoint23 waypoint24)
    (can_traverse rover0 waypoint5 waypoint0)
    (can_traverse rover0 waypoint0 waypoint5)
    (at rover1 waypoint4)
    (available rover1)
    (store_of rover1store rover1)
    (empty rover1store)
    (equipped_for_imaging rover1)
    (can_traverse rover1 waypoint4 waypoint1)
    (can_traverse rover1 waypoint1 waypoint4)
    (can_traverse rover1 waypoint4 waypoint5)
    (can_traverse rover1 waypoint5 waypoint4)
    (can_traverse rover1 waypoint4 waypoint6)
    (can_traverse rover1 waypoint6 waypoint4)
    (can_traverse rover1 waypoint4 waypoint13)
    (can_traverse rover1 waypoint13 waypoint4)
    (can_traverse rover1 waypoint4 waypoint16)
    (can_traverse rover1 waypoint16 waypoint4)
    (can_traverse rover1 waypoint4 waypoint19)
    (can_traverse rover1 waypoint19 waypoint4)
    (can_traverse rover1 waypoint4 waypoint20)
    (can_traverse rover1 waypoint20 waypoint4)
    (can_traverse rover1 waypoint4 waypoint21)
    (can_traverse rover1 waypoint21 waypoint4)
    (can_traverse rover1 waypoint1 waypoint14)
    (can_traverse rover1 waypoint14 waypoint1)
    (can_traverse rover1 waypoint1 waypoint15)
    (can_traverse rover1 waypoint15 waypoint1)
    (can_traverse rover1 waypoint1 waypoint18)
    (can_traverse rover1 waypoint18 waypoint1)
    (can_traverse rover1 waypoint5 waypoint0)
    (can_traverse rover1 waypoint0 waypoint5)
    (can_traverse rover1 waypoint5 waypoint2)
    (can_traverse rover1 waypoint2 waypoint5)
    (can_traverse rover1 waypoint5 waypoint8)
    (can_traverse rover1 waypoint8 waypoint5)
    (can_traverse rover1 waypoint5 waypoint9)
    (can_traverse rover1 waypoint9 waypoint5)
    (can_traverse rover1 waypoint5 waypoint24)
    (can_traverse rover1 waypoint24 waypoint5)
    (can_traverse rover1 waypoint6 waypoint11)
    (can_traverse rover1 waypoint11 waypoint6)
    (can_traverse rover1 waypoint6 waypoint12)
    (can_traverse rover1 waypoint12 waypoint6)
    (can_traverse rover1 waypoint13 waypoint3)
    (can_traverse rover1 waypoint3 waypoint13)
    (can_traverse rover1 waypoint16 waypoint22)
    (can_traverse rover1 waypoint22 waypoint16)
    (can_traverse rover1 waypoint20 waypoint17)
    (can_traverse rover1 waypoint17 waypoint20)
    (can_traverse rover1 waypoint18 waypoint10)
    (can_traverse rover1 waypoint10 waypoint18)
    (can_traverse rover1 waypoint18 waypoint23)
    (can_traverse rover1 waypoint23 waypoint18)
    (can_traverse rover1 waypoint0 waypoint7)
    (can_traverse rover1 waypoint7 waypoint0)
    (at rover2 waypoint3)
    (available rover2)
    (store_of rover2store rover2)
    (empty rover2store)
    (equipped_for_rock_analysis rover2)
    (equipped_for_imaging rover2)
    (can_traverse rover2 waypoint3 waypoint1)
    (can_traverse rover2 waypoint1 waypoint3)
    (can_traverse rover2 waypoint3 waypoint13)
    (can_traverse rover2 waypoint13 waypoint3)
    (can_traverse rover2 waypoint3 waypoint18)
    (can_traverse rover2 waypoint18 waypoint3)
    (can_traverse rover2 waypoint3 waypoint20)
    (can_traverse rover2 waypoint20 waypoint3)
    (can_traverse rover2 waypoint1 waypoint2)
    (can_traverse rover2 waypoint2 waypoint1)
    (can_traverse rover2 waypoint1 waypoint5)
    (can_traverse rover2 waypoint5 waypoint1)
    (can_traverse rover2 waypoint1 waypoint14)
    (can_traverse rover2 waypoint14 waypoint1)
    (can_traverse rover2 waypoint1 waypoint15)
    (can_traverse rover2 waypoint15 waypoint1)
    (can_traverse rover2 waypoint13 waypoint4)
    (can_traverse rover2 waypoint4 waypoint13)
    (can_traverse rover2 waypoint13 waypoint21)
    (can_traverse rover2 waypoint21 waypoint13)
    (can_traverse rover2 waypoint18 waypoint6)
    (can_traverse rover2 waypoint6 waypoint18)
    (can_traverse rover2 waypoint18 waypoint9)
    (can_traverse rover2 waypoint9 waypoint18)
    (can_traverse rover2 waypoint18 waypoint17)
    (can_traverse rover2 waypoint17 waypoint18)
    (can_traverse rover2 waypoint18 waypoint23)
    (can_traverse rover2 waypoint23 waypoint18)
    (can_traverse rover2 waypoint18 waypoint24)
    (can_traverse rover2 waypoint24 waypoint18)
    (can_traverse rover2 waypoint20 waypoint16)
    (can_traverse rover2 waypoint16 waypoint20)
    (can_traverse rover2 waypoint20 waypoint19)
    (can_traverse rover2 waypoint19 waypoint20)
    (can_traverse rover2 waypoint5 waypoint0)
    (can_traverse rover2 waypoint0 waypoint5)
    (can_traverse rover2 waypoint5 waypoint8)
    (can_traverse rover2 waypoint8 waypoint5)
    (can_traverse rover2 waypoint14 waypoint12)
    (can_traverse rover2 waypoint12 waypoint14)
    (can_traverse rover2 waypoint15 waypoint10)
    (can_traverse rover2 waypoint10 waypoint15)
    (can_traverse rover2 waypoint4 waypoint7)
    (can_traverse rover2 waypoint7 waypoint4)
    (can_traverse rover2 waypoint21 waypoint11)
    (can_traverse rover2 waypoint11 waypoint21)
    (can_traverse rover2 waypoint21 waypoint22)
    (can_traverse rover2 waypoint22 waypoint21)
    (at rover3 waypoint3)
    (available rover3)
    (store_of rover3store rover3)
    (empty rover3store)
    (equipped_for_soil_analysis rover3)
    (equipped_for_rock_analysis rover3)
    (can_traverse rover3 waypoint3 waypoint1)
    (can_traverse rover3 waypoint1 waypoint3)
    (can_traverse rover3 waypoint3 waypoint12)
    (can_traverse rover3 waypoint12 waypoint3)
    (can_traverse rover3 waypoint3 waypoint13)
    (can_traverse rover3 waypoint13 waypoint3)
    (can_traverse rover3 waypoint3 waypoint18)
    (can_traverse rover3 waypoint18 waypoint3)
    (can_traverse rover3 waypoint3 waypoint20)
    (can_traverse rover3 waypoint20 waypoint3)
    (can_traverse rover3 waypoint1 waypoint2)
    (can_traverse rover3 waypoint2 waypoint1)
    (can_traverse rover3 waypoint1 waypoint4)
    (can_traverse rover3 waypoint4 waypoint1)
    (can_traverse rover3 waypoint1 waypoint5)
    (can_traverse rover3 waypoint5 waypoint1)
    (can_traverse rover3 waypoint1 waypoint14)
    (can_traverse rover3 waypoint14 waypoint1)
    (can_traverse rover3 waypoint1 waypoint15)
    (can_traverse rover3 waypoint15 waypoint1)
    (can_traverse rover3 waypoint1 waypoint23)
    (can_traverse rover3 waypoint23 waypoint1)
    (can_traverse rover3 waypoint12 waypoint6)
    (can_traverse rover3 waypoint6 waypoint12)
    (can_traverse rover3 waypoint12 waypoint19)
    (can_traverse rover3 waypoint19 waypoint12)
    (can_traverse rover3 waypoint12 waypoint22)
    (can_traverse rover3 waypoint22 waypoint12)
    (can_traverse rover3 waypoint12 waypoint24)
    (can_traverse rover3 waypoint24 waypoint12)
    (can_traverse rover3 waypoint13 waypoint21)
    (can_traverse rover3 waypoint21 waypoint13)
    (can_traverse rover3 waypoint18 waypoint0)
    (can_traverse rover3 waypoint0 waypoint18)
    (can_traverse rover3 waypoint18 waypoint9)
    (can_traverse rover3 waypoint9 waypoint18)
    (can_traverse rover3 waypoint18 waypoint17)
    (can_traverse rover3 waypoint17 waypoint18)
    (can_traverse rover3 waypoint20 waypoint16)
    (can_traverse rover3 waypoint16 waypoint20)
    (can_traverse rover3 waypoint4 waypoint7)
    (can_traverse rover3 waypoint7 waypoint4)
    (can_traverse rover3 waypoint4 waypoint8)
    (can_traverse rover3 waypoint8 waypoint4)
    (can_traverse rover3 waypoint6 waypoint11)
    (can_traverse rover3 waypoint11 waypoint6)
    (can_traverse rover3 waypoint16 waypoint10)
    (can_traverse rover3 waypoint10 waypoint16)
    (at rover4 waypoint16)
    (available rover4)
    (store_of rover4store rover4)
    (empty rover4store)
    (equipped_for_rock_analysis rover4)
    (equipped_for_imaging rover4)
    (can_traverse rover4 waypoint16 waypoint2)
    (can_traverse rover4 waypoint2 waypoint16)
    (can_traverse rover4 waypoint16 waypoint4)
    (can_traverse rover4 waypoint4 waypoint16)
    (can_traverse rover4 waypoint16 waypoint5)
    (can_traverse rover4 waypoint5 waypoint16)
    (can_traverse rover4 waypoint16 waypoint7)
    (can_traverse rover4 waypoint7 waypoint16)
    (can_traverse rover4 waypoint16 waypoint8)
    (can_traverse rover4 waypoint8 waypoint16)
    (can_traverse rover4 waypoint16 waypoint10)
    (can_traverse rover4 waypoint10 waypoint16)
    (can_traverse rover4 waypoint16 waypoint15)
    (can_traverse rover4 waypoint15 waypoint16)
    (can_traverse rover4 waypoint16 waypoint22)
    (can_traverse rover4 waypoint22 waypoint16)
    (can_traverse rover4 waypoint2 waypoint9)
    (can_traverse rover4 waypoint9 waypoint2)
    (can_traverse rover4 waypoint2 waypoint14)
    (can_traverse rover4 waypoint14 waypoint2)
    (can_traverse rover4 waypoint4 waypoint1)
    (can_traverse rover4 waypoint1 waypoint4)
    (can_traverse rover4 waypoint4 waypoint13)
    (can_traverse rover4 waypoint13 waypoint4)
    (can_traverse rover4 waypoint4 waypoint20)
    (can_traverse rover4 waypoint20 waypoint4)
    (can_traverse rover4 waypoint5 waypoint0)
    (can_traverse rover4 waypoint0 waypoint5)
    (can_traverse rover4 waypoint5 waypoint21)
    (can_traverse rover4 waypoint21 waypoint5)
    (can_traverse rover4 waypoint5 waypoint24)
    (can_traverse rover4 waypoint24 waypoint5)
    (can_traverse rover4 waypoint7 waypoint17)
    (can_traverse rover4 waypoint17 waypoint7)
    (can_traverse rover4 waypoint8 waypoint11)
    (can_traverse rover4 waypoint11 waypoint8)
    (can_traverse rover4 waypoint8 waypoint18)
    (can_traverse rover4 waypoint18 waypoint8)
    (can_traverse rover4 waypoint15 waypoint3)
    (can_traverse rover4 waypoint3 waypoint15)
    (can_traverse rover4 waypoint15 waypoint6)
    (can_traverse rover4 waypoint6 waypoint15)
    (can_traverse rover4 waypoint15 waypoint12)
    (can_traverse rover4 waypoint12 waypoint15)
    (can_traverse rover4 waypoint20 waypoint23)
    (can_traverse rover4 waypoint23 waypoint20)
    (can_traverse rover4 waypoint21 waypoint19)
    (can_traverse rover4 waypoint19 waypoint21)
    (at rover5 waypoint10)
    (available rover5)
    (store_of rover5store rover5)
    (empty rover5store)
    (equipped_for_imaging rover5)
    (can_traverse rover5 waypoint10 waypoint11)
    (can_traverse rover5 waypoint11 waypoint10)
    (can_traverse rover5 waypoint10 waypoint15)
    (can_traverse rover5 waypoint15 waypoint10)
    (can_traverse rover5 waypoint10 waypoint16)
    (can_traverse rover5 waypoint16 waypoint10)
    (can_traverse rover5 waypoint10 waypoint18)
    (can_traverse rover5 waypoint18 waypoint10)
    (can_traverse rover5 waypoint10 waypoint23)
    (can_traverse rover5 waypoint23 waypoint10)
    (can_traverse rover5 waypoint11 waypoint6)
    (can_traverse rover5 waypoint6 waypoint11)
    (can_traverse rover5 waypoint11 waypoint8)
    (can_traverse rover5 waypoint8 waypoint11)
    (can_traverse rover5 waypoint11 waypoint12)
    (can_traverse rover5 waypoint12 waypoint11)
    (can_traverse rover5 waypoint11 waypoint21)
    (can_traverse rover5 waypoint21 waypoint11)
    (can_traverse rover5 waypoint11 waypoint22)
    (can_traverse rover5 waypoint22 waypoint11)
    (can_traverse rover5 waypoint15 waypoint0)
    (can_traverse rover5 waypoint0 waypoint15)
    (can_traverse rover5 waypoint15 waypoint1)
    (can_traverse rover5 waypoint1 waypoint15)
    (can_traverse rover5 waypoint15 waypoint13)
    (can_traverse rover5 waypoint13 waypoint15)
    (can_traverse rover5 waypoint15 waypoint17)
    (can_traverse rover5 waypoint17 waypoint15)
    (can_traverse rover5 waypoint16 waypoint2)
    (can_traverse rover5 waypoint2 waypoint16)
    (can_traverse rover5 waypoint16 waypoint4)
    (can_traverse rover5 waypoint4 waypoint16)
    (can_traverse rover5 waypoint16 waypoint7)
    (can_traverse rover5 waypoint7 waypoint16)
    (can_traverse rover5 waypoint18 waypoint3)
    (can_traverse rover5 waypoint3 waypoint18)
    (can_traverse rover5 waypoint23 waypoint20)
    (can_traverse rover5 waypoint20 waypoint23)
    (can_traverse rover5 waypoint23 waypoint24)
    (can_traverse rover5 waypoint24 waypoint23)
    (can_traverse rover5 waypoint6 waypoint5)
    (can_traverse rover5 waypoint5 waypoint6)
    (can_traverse rover5 waypoint6 waypoint9)
    (can_traverse rover5 waypoint9 waypoint6)
    (can_traverse rover5 waypoint6 waypoint14)
    (can_traverse rover5 waypoint14 waypoint6)
    (can_traverse rover5 waypoint6 waypoint19)
    (can_traverse rover5 waypoint19 waypoint6)
    (at rover6 waypoint4)
    (available rover6)
    (store_of rover6store rover6)
    (empty rover6store)
    (equipped_for_soil_analysis rover6)
    (equipped_for_imaging rover6)
    (can_traverse rover6 waypoint4 waypoint1)
    (can_traverse rover6 waypoint1 waypoint4)
    (can_traverse rover6 waypoint4 waypoint6)
    (can_traverse rover6 waypoint6 waypoint4)
    (can_traverse rover6 waypoint4 waypoint8)
    (can_traverse rover6 waypoint8 waypoint4)
    (can_traverse rover6 waypoint4 waypoint13)
    (can_traverse rover6 waypoint13 waypoint4)
    (can_traverse rover6 waypoint4 waypoint16)
    (can_traverse rover6 waypoint16 waypoint4)
    (can_traverse rover6 waypoint4 waypoint19)
    (can_traverse rover6 waypoint19 waypoint4)
    (can_traverse rover6 waypoint4 waypoint20)
    (can_traverse rover6 waypoint20 waypoint4)
    (can_traverse rover6 waypoint1 waypoint3)
    (can_traverse rover6 waypoint3 waypoint1)
    (can_traverse rover6 waypoint1 waypoint5)
    (can_traverse rover6 waypoint5 waypoint1)
    (can_traverse rover6 waypoint1 waypoint14)
    (can_traverse rover6 waypoint14 waypoint1)
    (can_traverse rover6 waypoint1 waypoint18)
    (can_traverse rover6 waypoint18 waypoint1)
    (can_traverse rover6 waypoint1 waypoint23)
    (can_traverse rover6 waypoint23 waypoint1)
    (can_traverse rover6 waypoint6 waypoint2)
    (can_traverse rover6 waypoint2 waypoint6)
    (can_traverse rover6 waypoint6 waypoint9)
    (can_traverse rover6 waypoint9 waypoint6)
    (can_traverse rover6 waypoint6 waypoint11)
    (can_traverse rover6 waypoint11 waypoint6)
    (can_traverse rover6 waypoint6 waypoint12)
    (can_traverse rover6 waypoint12 waypoint6)
    (can_traverse rover6 waypoint6 waypoint15)
    (can_traverse rover6 waypoint15 waypoint6)
    (can_traverse rover6 waypoint6 waypoint21)
    (can_traverse rover6 waypoint21 waypoint6)
    (can_traverse rover6 waypoint8 waypoint17)
    (can_traverse rover6 waypoint17 waypoint8)
    (can_traverse rover6 waypoint16 waypoint7)
    (can_traverse rover6 waypoint7 waypoint16)
    (can_traverse rover6 waypoint16 waypoint10)
    (can_traverse rover6 waypoint10 waypoint16)
    (can_traverse rover6 waypoint16 waypoint22)
    (can_traverse rover6 waypoint22 waypoint16)
    (can_traverse rover6 waypoint20 waypoint24)
    (can_traverse rover6 waypoint24 waypoint20)
    (can_traverse rover6 waypoint23 waypoint0)
    (can_traverse rover6 waypoint0 waypoint23)
    (at rover7 waypoint16)
    (available rover7)
    (store_of rover7store rover7)
    (empty rover7store)
    (equipped_for_rock_analysis rover7)
    (can_traverse rover7 waypoint16 waypoint2)
    (can_traverse rover7 waypoint2 waypoint16)
    (can_traverse rover7 waypoint16 waypoint4)
    (can_traverse rover7 waypoint4 waypoint16)
    (can_traverse rover7 waypoint16 waypoint8)
    (can_traverse rover7 waypoint8 waypoint16)
    (can_traverse rover7 waypoint16 waypoint10)
    (can_traverse rover7 waypoint10 waypoint16)
    (can_traverse rover7 waypoint16 waypoint20)
    (can_traverse rover7 waypoint20 waypoint16)
    (can_traverse rover7 waypoint2 waypoint5)
    (can_traverse rover7 waypoint5 waypoint2)
    (can_traverse rover7 waypoint2 waypoint6)
    (can_traverse rover7 waypoint6 waypoint2)
    (can_traverse rover7 waypoint2 waypoint9)
    (can_traverse rover7 waypoint9 waypoint2)
    (can_traverse rover7 waypoint2 waypoint14)
    (can_traverse rover7 waypoint14 waypoint2)
    (can_traverse rover7 waypoint2 waypoint23)
    (can_traverse rover7 waypoint23 waypoint2)
    (can_traverse rover7 waypoint4 waypoint13)
    (can_traverse rover7 waypoint13 waypoint4)
    (can_traverse rover7 waypoint4 waypoint19)
    (can_traverse rover7 waypoint19 waypoint4)
    (can_traverse rover7 waypoint8 waypoint7)
    (can_traverse rover7 waypoint7 waypoint8)
    (can_traverse rover7 waypoint8 waypoint17)
    (can_traverse rover7 waypoint17 waypoint8)
    (can_traverse rover7 waypoint8 waypoint18)
    (can_traverse rover7 waypoint18 waypoint8)
    (can_traverse rover7 waypoint10 waypoint11)
    (can_traverse rover7 waypoint11 waypoint10)
    (can_traverse rover7 waypoint10 waypoint15)
    (can_traverse rover7 waypoint15 waypoint10)
    (can_traverse rover7 waypoint20 waypoint3)
    (can_traverse rover7 waypoint3 waypoint20)
    (can_traverse rover7 waypoint20 waypoint24)
    (can_traverse rover7 waypoint24 waypoint20)
    (can_traverse rover7 waypoint5 waypoint21)
    (can_traverse rover7 waypoint21 waypoint5)
    (can_traverse rover7 waypoint6 waypoint12)
    (can_traverse rover7 waypoint12 waypoint6)
    (can_traverse rover7 waypoint14 waypoint0)
    (can_traverse rover7 waypoint0 waypoint14)
    (can_traverse rover7 waypoint14 waypoint1)
    (can_traverse rover7 waypoint1 waypoint14)
    (on_board camera0 rover0)
    (calibration_target camera0 objective6)
    (supports camera0 colour)
    (supports camera0 high_res)
    (on_board camera1 rover1)
    (calibration_target camera1 objective1)
    (supports camera1 colour)
    (supports camera1 high_res)
    (on_board camera2 rover4)
    (calibration_target camera2 objective0)
    (supports camera2 colour)
    (supports camera2 high_res)
    (supports camera2 low_res)
    (on_board camera3 rover2)
    (calibration_target camera3 objective2)
    (supports camera3 high_res)
    (supports camera3 low_res)
    (on_board camera4 rover1)
    (calibration_target camera4 objective4)
    (supports camera4 colour)
    (supports camera4 high_res)
    (on_board camera5 rover5)
    (calibration_target camera5 objective4)
    (supports camera5 high_res)
    (on_board camera6 rover6)
    (calibration_target camera6 objective5)
    (supports camera6 colour)
    (supports camera6 high_res)
    (supports camera6 low_res)
    (visible_from objective0 waypoint0)
    (visible_from objective0 waypoint1)
    (visible_from objective0 waypoint2)
    (visible_from objective0 waypoint3)
    (visible_from objective0 waypoint4)
    (visible_from objective0 waypoint5)
    (visible_from objective0 waypoint6)
    (visible_from objective0 waypoint7)
    (visible_from objective0 waypoint8)
    (visible_from objective0 waypoint9)
    (visible_from objective0 waypoint10)
    (visible_from objective0 waypoint11)
    (visible_from objective0 waypoint12)
    (visible_from objective0 waypoint13)
    (visible_from objective0 waypoint14)
    (visible_from objective0 waypoint15)
    (visible_from objective0 waypoint16)
    (visible_from objective1 waypoint0)
    (visible_from objective1 waypoint1)
    (visible_from objective1 waypoint2)
    (visible_from objective1 waypoint3)
    (visible_from objective2 waypoint0)
    (visible_from objective2 waypoint1)
    (visible_from objective2 waypoint2)
    (visible_from objective2 waypoint3)
    (visible_from objective2 waypoint4)
    (visible_from objective2 waypoint5)
    (visible_from objective2 waypoint6)
    (visible_from objective2 waypoint7)
    (visible_from objective2 waypoint8)
    (visible_from objective2 waypoint9)
    (visible_from objective2 waypoint10)
    (visible_from objective2 waypoint11)
    (visible_from objective2 waypoint12)
    (visible_from objective2 waypoint13)
    (visible_from objective2 waypoint14)
    (visible_from objective2 waypoint15)
    (visible_from objective2 waypoint16)
    (visible_from objective2 waypoint17)
    (visible_from objective3 waypoint0)
    (visible_from objective3 waypoint1)
    (visible_from objective3 waypoint2)
    (visible_from objective3 waypoint3)
    (visible_from objective3 waypoint4)
    (visible_from objective3 waypoint5)
    (visible_from objective3 waypoint6)
    (visible_from objective3 waypoint7)
    (visible_from objective3 waypoint8)
    (visible_from objective3 waypoint9)
    (visible_from objective3 waypoint10)
    (visible_from objective3 waypoint11)
    (visible_from objective3 waypoint12)
    (visible_from objective3 waypoint13)
    (visible_from objective3 waypoint14)
    (visible_from objective3 waypoint15)
    (visible_from objective3 waypoint16)
    (visible_from objective3 waypoint17)
    (visible_from objective3 waypoint18)
    (visible_from objective3 waypoint19)
    (visible_from objective4 waypoint0)
    (visible_from objective4 waypoint1)
    (visible_from objective4 waypoint2)
    (visible_from objective4 waypoint3)
    (visible_from objective4 waypoint4)
    (visible_from objective4 waypoint5)
    (visible_from objective4 waypoint6)
    (visible_from objective4 waypoint7)
    (visible_from objective4 waypoint8)
    (visible_from objective4 waypoint9)
    (visible_from objective4 waypoint10)
    (visible_from objective4 waypoint11)
    (visible_from objective4 waypoint12)
    (visible_from objective4 waypoint13)
    (visible_from objective4 waypoint14)
    (visible_from objective4 waypoint15)
    (visible_from objective4 waypoint16)
    (visible_from objective4 waypoint17)
    (visible_from objective4 waypoint18)
    (visible_from objective4 waypoint19)
    (visible_from objective4 waypoint20)
    (visible_from objective4 waypoint21)
    (visible_from objective4 waypoint22)
    (visible_from objective4 waypoint23)
    (visible_from objective5 waypoint0)
    (visible_from objective5 waypoint1)
    (visible_from objective5 waypoint2)
    (visible_from objective5 waypoint3)
    (visible_from objective5 waypoint4)
    (visible_from objective5 waypoint5)
    (visible_from objective5 waypoint6)
    (visible_from objective5 waypoint7)
    (visible_from objective5 waypoint8)
    (visible_from objective5 waypoint9)
    (visible_from objective5 waypoint10)
    (visible_from objective5 waypoint11)
    (visible_from objective5 waypoint12)
    (visible_from objective5 waypoint13)
    (visible_from objective5 waypoint14)
    (visible_from objective6 waypoint0)
    (visible_from objective6 waypoint1)
    (visible_from objective6 waypoint2)
    (visible_from objective6 waypoint3)
    (visible_from objective6 waypoint4)
    (visible_from objective6 waypoint5)
    (visible_from objective6 waypoint6)
    (visible_from objective6 waypoint7)
    (visible_from objective6 waypoint8)
    (visible_from objective6 waypoint9)
    (visible_from objective6 waypoint10)
    (visible_from objective7 waypoint0)
    (visible_from objective7 waypoint1)
    (visible_from objective7 waypoint2)
    (visible_from objective7 waypoint3)
    (visible_from objective7 waypoint4)
    (visible_from objective7 waypoint5)
    (visible_from objective7 waypoint6)
    (visible_from objective7 waypoint7)
    (visible_from objective7 waypoint8)
    (visible_from objective7 waypoint9)
    (visible_from objective7 waypoint10)
    (visible_from objective7 waypoint11)
    (visible_from objective7 waypoint12)
    (visible_from objective7 waypoint13)
    (visible_from objective7 waypoint14)
    (visible_from objective7 waypoint15)
    (visible_from objective7 waypoint16)
    (visible_from objective7 waypoint17)
    (visible_from objective7 waypoint18)
    (visible_from objective7 waypoint19)
    (visible_from objective7 waypoint20)
    (type_camera camera0)
    (type_camera camera1)
    (type_camera camera2)
    (type_camera camera3)
    (type_camera camera4)
    (type_camera camera5)
    (type_camera camera6)
    (type_lander general)
    (type_mode colour)
    (type_mode high_res)
    (type_mode low_res)
    (type_object camera0)
    (type_object camera1)
    (type_object camera2)
    (type_object camera3)
    (type_object camera4)
    (type_object camera5)
    (type_object camera6)
    (type_object colour)
    (type_object general)
    (type_object high_res)
    (type_object low_res)
    (type_object objective0)
    (type_object objective1)
    (type_object objective2)
    (type_object objective3)
    (type_object objective4)
    (type_object objective5)
    (type_object objective6)
    (type_object objective7)
    (type_object rover0)
    (type_object rover0store)
    (type_object rover1)
    (type_object rover1store)
    (type_object rover2)
    (type_object rover2store)
    (type_object rover3)
    (type_object rover3store)
    (type_object rover4)
    (type_object rover4store)
    (type_object rover5)
    (type_object rover5store)
    (type_object rover6)
    (type_object rover6store)
    (type_object rover7)
    (type_object rover7store)
    (type_object waypoint0)
    (type_object waypoint1)
    (type_object waypoint10)
    (type_object waypoint11)
    (type_object waypoint12)
    (type_object waypoint13)
    (type_object waypoint14)
    (type_object waypoint15)
    (type_object waypoint16)
    (type_object waypoint17)
    (type_object waypoint18)
    (type_object waypoint19)
    (type_object waypoint2)
    (type_object waypoint20)
    (type_object waypoint21)
    (type_object waypoint22)
    (type_object waypoint23)
    (type_object waypoint24)
    (type_object waypoint3)
    (type_object waypoint4)
    (type_object waypoint5)
    (type_object waypoint6)
    (type_object waypoint7)
    (type_object waypoint8)
    (type_object waypoint9)
    (type_objective objective0)
    (type_objective objective1)
    (type_objective objective2)
    (type_objective objective3)
    (type_objective objective4)
    (type_objective objective5)
    (type_objective objective6)
    (type_objective objective7)
    (type_rover rover0)
    (type_rover rover1)
    (type_rover rover2)
    (type_rover rover3)
    (type_rover rover4)
    (type_rover rover5)
    (type_rover rover6)
    (type_rover rover7)
    (type_sort_for_camera0 camera0)
    (type_sort_for_camera1 camera1)
    (type_sort_for_camera2 camera2)
    (type_sort_for_camera3 camera3)
    (type_sort_for_camera4 camera4)
    (type_sort_for_camera5 camera5)
    (type_sort_for_camera6 camera6)
    (type_sort_for_colour colour)
    (type_sort_for_general general)
    (type_sort_for_high_res high_res)
    (type_sort_for_low_res low_res)
    (type_sort_for_objective0 objective0)
    (type_sort_for_objective1 objective1)
    (type_sort_for_objective2 objective2)
    (type_sort_for_objective3 objective3)
    (type_sort_for_objective4 objective4)
    (type_sort_for_objective5 objective5)
    (type_sort_for_objective6 objective6)
    (type_sort_for_objective7 objective7)
    (type_sort_for_rover0 rover0)
    (type_sort_for_rover0store rover0store)
    (type_sort_for_rover1 rover1)
    (type_sort_for_rover1store rover1store)
    (type_sort_for_rover2 rover2)
    (type_sort_for_rover2store rover2store)
    (type_sort_for_rover3 rover3)
    (type_sort_for_rover3store rover3store)
    (type_sort_for_rover4 rover4)
    (type_sort_for_rover4store rover4store)
    (type_sort_for_rover5 rover5)
    (type_sort_for_rover5store rover5store)
    (type_sort_for_rover6 rover6)
    (type_sort_for_rover6store rover6store)
    (type_sort_for_rover7 rover7)
    (type_sort_for_rover7store rover7store)
    (type_sort_for_waypoint0 waypoint0)
    (type_sort_for_waypoint1 waypoint1)
    (type_sort_for_waypoint10 waypoint10)
    (type_sort_for_waypoint11 waypoint11)
    (type_sort_for_waypoint12 waypoint12)
    (type_sort_for_waypoint13 waypoint13)
    (type_sort_for_waypoint14 waypoint14)
    (type_sort_for_waypoint15 waypoint15)
    (type_sort_for_waypoint16 waypoint16)
    (type_sort_for_waypoint17 waypoint17)
    (type_sort_for_waypoint18 waypoint18)
    (type_sort_for_waypoint19 waypoint19)
    (type_sort_for_waypoint2 waypoint2)
    (type_sort_for_waypoint20 waypoint20)
    (type_sort_for_waypoint21 waypoint21)
    (type_sort_for_waypoint22 waypoint22)
    (type_sort_for_waypoint23 waypoint23)
    (type_sort_for_waypoint24 waypoint24)
    (type_sort_for_waypoint3 waypoint3)
    (type_sort_for_waypoint4 waypoint4)
    (type_sort_for_waypoint5 waypoint5)
    (type_sort_for_waypoint6 waypoint6)
    (type_sort_for_waypoint7 waypoint7)
    (type_sort_for_waypoint8 waypoint8)
    (type_sort_for_waypoint9 waypoint9)
    (type_store rover0store)
    (type_store rover1store)
    (type_store rover2store)
    (type_store rover3store)
    (type_store rover4store)
    (type_store rover5store)
    (type_store rover6store)
    (type_store rover7store)
    (type_waypoint waypoint0)
    (type_waypoint waypoint1)
    (type_waypoint waypoint10)
    (type_waypoint waypoint11)
    (type_waypoint waypoint12)
    (type_waypoint waypoint13)
    (type_waypoint waypoint14)
    (type_waypoint waypoint15)
    (type_waypoint waypoint16)
    (type_waypoint waypoint17)
    (type_waypoint waypoint18)
    (type_waypoint waypoint19)
    (type_waypoint waypoint2)
    (type_waypoint waypoint20)
    (type_waypoint waypoint21)
    (type_waypoint waypoint22)
    (type_waypoint waypoint23)
    (type_waypoint waypoint24)
    (type_waypoint waypoint3)
    (type_waypoint waypoint4)
    (type_waypoint waypoint5)
    (type_waypoint waypoint6)
    (type_waypoint waypoint7)
    (type_waypoint waypoint8)
    (type_waypoint waypoint9)
  )
  ((__top))
)
