(defproblem problem domain 
  (
    (In_City HauptbahnhofUlm Ulm)
    (In_City HauptbahnhofStuttgart Stuttgart)
    (At_Vehicle Eisenbahnwagen HauptbahnhofUlm)
    (At_Vehicle Lokomotive HauptbahnhofUlm)
    (Connects UlmStuttgartRailRoute HauptbahnhofUlm HauptbahnhofStuttgart)
    (Available UlmStuttgartRailRoute)
    (Available Lokomotive)
    (PV_Compatible MaseratiMC12 Eisenbahnwagen)
    (RV_Compatible UlmStuttgartRailRoute Lokomotive)
    (At_Package MaseratiMC12 HauptbahnhofUlm)
    (type_Auto Eisenbahnwagen)
    (type_Auto MaseratiMC12)
    (type_Auto_Traincar Eisenbahnwagen)
    (type_Auto_Vehicle Eisenbahnwagen)
    (type_Cars MaseratiMC12)
    (type_City Stuttgart)
    (type_City Ulm)
    (type_City_Location HauptbahnhofStuttgart)
    (type_City_Location HauptbahnhofUlm)
    (type_Equipment_Position Eisenbahnwagen)
    (type_Equipment_Position HauptbahnhofStuttgart)
    (type_Equipment_Position HauptbahnhofUlm)
    (type_Equipment_Position Lokomotive)
    (type_Equipment_Position Stuttgart)
    (type_Equipment_Position Ulm)
    (type_Location HauptbahnhofStuttgart)
    (type_Location HauptbahnhofUlm)
    (type_Location Stuttgart)
    (type_Location Ulm)
    (type_Object Eisenbahnwagen)
    (type_Object Lokomotive)
    (type_Object MaseratiMC12)
    (type_Package MaseratiMC12)
    (type_Package_Storage_Position Eisenbahnwagen)
    (type_Package_Storage_Position HauptbahnhofStuttgart)
    (type_Package_Storage_Position HauptbahnhofUlm)
    (type_Package_Storage_Position Lokomotive)
    (type_Package_Storage_Position Stuttgart)
    (type_Package_Storage_Position Ulm)
    (type_Physical Eisenbahnwagen)
    (type_Physical MaseratiMC12)
    (type_Rail_Route UlmStuttgartRailRoute)
    (type_Route UlmStuttgartRailRoute)
    (type_TCenter HauptbahnhofStuttgart)
    (type_TCenter HauptbahnhofUlm)
    (type_Thing Eisenbahnwagen)
    (type_Thing HauptbahnhofStuttgart)
    (type_Thing HauptbahnhofUlm)
    (type_Thing Lokomotive)
    (type_Thing MaseratiMC12)
    (type_Thing Stuttgart)
    (type_Thing Ulm)
    (type_Thing UlmStuttgartRailRoute)
    (type_Train Lokomotive)
    (type_Train_Station HauptbahnhofStuttgart)
    (type_Train_Station HauptbahnhofUlm)
    (type_Traincar Eisenbahnwagen)
    (type_Vehicle Eisenbahnwagen)
    (type_Vehicle Lokomotive)
    (type_Vehicle_Position Eisenbahnwagen)
    (type_Vehicle_Position HauptbahnhofStuttgart)
    (type_Vehicle_Position HauptbahnhofUlm)
    (type_Vehicle_Position Stuttgart)
    (type_Vehicle_Position Ulm)
    (type_sort_for_Eisenbahnwagen Eisenbahnwagen)
    (type_sort_for_HauptbahnhofStuttgart HauptbahnhofStuttgart)
    (type_sort_for_HauptbahnhofUlm HauptbahnhofUlm)
    (type_sort_for_Lokomotive Lokomotive)
    (type_sort_for_MaseratiMC12 MaseratiMC12)
    (type_sort_for_Stuttgart Stuttgart)
    (type_sort_for_Ulm Ulm)
    (type_sort_for_UlmStuttgartRailRoute UlmStuttgartRailRoute)
  )
  ((__top))
)
