(defproblem problem domain 
  (
    (In_City HauptbahnhofUlm Ulm)
    (In_City HauptbahnhofMuenchen Muenchen)
    (At_Vehicle Eisenbahnwagen HauptbahnhofUlm)
    (At_Vehicle Lokomotive HauptbahnhofUlm)
    (Connects UlmMuenchenRailRoute HauptbahnhofUlm HauptbahnhofMuenchen)
    (Available UlmMuenchenRailRoute)
    (Available Lokomotive)
    (PV_Compatible Briefe Eisenbahnwagen)
    (RV_Compatible UlmMuenchenRailRoute Lokomotive)
    (At_Package Briefe HauptbahnhofUlm)
    (type_City Muenchen)
    (type_City Ulm)
    (type_City_Location HauptbahnhofMuenchen)
    (type_City_Location HauptbahnhofUlm)
    (type_Equipment_Position Eisenbahnwagen)
    (type_Equipment_Position HauptbahnhofMuenchen)
    (type_Equipment_Position HauptbahnhofUlm)
    (type_Equipment_Position Lokomotive)
    (type_Equipment_Position Muenchen)
    (type_Equipment_Position Ulm)
    (type_Location HauptbahnhofMuenchen)
    (type_Location HauptbahnhofUlm)
    (type_Location Muenchen)
    (type_Location Ulm)
    (type_Mail Briefe)
    (type_Mail Eisenbahnwagen)
    (type_Mail_Package Briefe)
    (type_Mail_Traincar Eisenbahnwagen)
    (type_Mail_Vehicle Eisenbahnwagen)
    (type_Object Briefe)
    (type_Object Eisenbahnwagen)
    (type_Object Lokomotive)
    (type_Package Briefe)
    (type_Package_Storage_Position Eisenbahnwagen)
    (type_Package_Storage_Position HauptbahnhofMuenchen)
    (type_Package_Storage_Position HauptbahnhofUlm)
    (type_Package_Storage_Position Lokomotive)
    (type_Package_Storage_Position Muenchen)
    (type_Package_Storage_Position Ulm)
    (type_Physical Briefe)
    (type_Physical Eisenbahnwagen)
    (type_Rail_Route UlmMuenchenRailRoute)
    (type_Regular Briefe)
    (type_Regular Eisenbahnwagen)
    (type_Regular_Vehicle Eisenbahnwagen)
    (type_Route UlmMuenchenRailRoute)
    (type_TCenter HauptbahnhofMuenchen)
    (type_TCenter HauptbahnhofUlm)
    (type_Thing Briefe)
    (type_Thing Eisenbahnwagen)
    (type_Thing HauptbahnhofMuenchen)
    (type_Thing HauptbahnhofUlm)
    (type_Thing Lokomotive)
    (type_Thing Muenchen)
    (type_Thing Ulm)
    (type_Thing UlmMuenchenRailRoute)
    (type_Train Lokomotive)
    (type_Train_Station HauptbahnhofMuenchen)
    (type_Train_Station HauptbahnhofUlm)
    (type_Traincar Eisenbahnwagen)
    (type_Vehicle Eisenbahnwagen)
    (type_Vehicle Lokomotive)
    (type_Vehicle_Position Eisenbahnwagen)
    (type_Vehicle_Position HauptbahnhofMuenchen)
    (type_Vehicle_Position HauptbahnhofUlm)
    (type_Vehicle_Position Muenchen)
    (type_Vehicle_Position Ulm)
    (type_sort_for_Briefe Briefe)
    (type_sort_for_Eisenbahnwagen Eisenbahnwagen)
    (type_sort_for_HauptbahnhofMuenchen HauptbahnhofMuenchen)
    (type_sort_for_HauptbahnhofUlm HauptbahnhofUlm)
    (type_sort_for_Lokomotive Lokomotive)
    (type_sort_for_Muenchen Muenchen)
    (type_sort_for_Ulm Ulm)
    (type_sort_for_UlmMuenchenRailRoute UlmMuenchenRailRoute)
  )
  ((__top))
)
