(defproblem problem domain 
  (
    (In_Region Stuttgart BadenWuerttemberg)
    (In_Region London LondonRegion)
    (In_City HauptbahnhofStuttgart Stuttgart)
    (Available HauptbahnhofStuttgart)
    (In_City LondonWaterloo London)
    (Available LondonWaterloo)
    (Available GareParisNord)
    (In_City GareParisNord Paris)
    (City_Hazardous_Compatible Paris)
    (Serves GareParisNord BadenWuerttemberg)
    (Serves GareParisNord LondonRegion)
    (At_Vehicle LokomotiveDB HauptbahnhofStuttgart)
    (At_Vehicle LokomotiveSNCF GareParisNord)
    (At_Vehicle Eisenbahnwagen HauptbahnhofStuttgart)
    (Connects Stuttgart_Paris_Rail_Route HauptbahnhofStuttgart GareParisNord)
    (Connects Paris_London_Rail_Route GareParisNord LondonWaterloo)
    (Available Stuttgart_Paris_Rail_Route)
    (Available Paris_London_Rail_Route)
    (Available LokomotiveDB)
    (Available LokomotiveSNCF)
    (PV_Compatible Chemicalien Eisenbahnwagen)
    (RV_Compatible Stuttgart_Paris_Rail_Route LokomotiveDB)
    (RV_Compatible Paris_London_Rail_Route LokomotiveSNCF)
    (At_Package Chemicalien HauptbahnhofStuttgart)
    (type_Chemicals Chemicalien)
    (type_City London)
    (type_City Paris)
    (type_City Stuttgart)
    (type_City_Location GareParisNord)
    (type_City_Location HauptbahnhofStuttgart)
    (type_City_Location LondonWaterloo)
    (type_Equipment_Position BadenWuerttemberg)
    (type_Equipment_Position Eisenbahnwagen)
    (type_Equipment_Position GareParisNord)
    (type_Equipment_Position HauptbahnhofStuttgart)
    (type_Equipment_Position LokomotiveDB)
    (type_Equipment_Position LokomotiveSNCF)
    (type_Equipment_Position London)
    (type_Equipment_Position LondonRegion)
    (type_Equipment_Position LondonWaterloo)
    (type_Equipment_Position Paris)
    (type_Equipment_Position Stuttgart)
    (type_Hazardous Chemicalien)
    (type_Hub GareParisNord)
    (type_Liquid Chemicalien)
    (type_Location BadenWuerttemberg)
    (type_Location GareParisNord)
    (type_Location HauptbahnhofStuttgart)
    (type_Location London)
    (type_Location LondonRegion)
    (type_Location LondonWaterloo)
    (type_Location Paris)
    (type_Location Stuttgart)
    (type_Object Chemicalien)
    (type_Object Eisenbahnwagen)
    (type_Object LokomotiveDB)
    (type_Object LokomotiveSNCF)
    (type_Package Chemicalien)
    (type_Package_Storage_Position BadenWuerttemberg)
    (type_Package_Storage_Position Eisenbahnwagen)
    (type_Package_Storage_Position GareParisNord)
    (type_Package_Storage_Position HauptbahnhofStuttgart)
    (type_Package_Storage_Position LokomotiveDB)
    (type_Package_Storage_Position LokomotiveSNCF)
    (type_Package_Storage_Position London)
    (type_Package_Storage_Position LondonRegion)
    (type_Package_Storage_Position LondonWaterloo)
    (type_Package_Storage_Position Paris)
    (type_Package_Storage_Position Stuttgart)
    (type_Perishable Chemicalien)
    (type_Physical Chemicalien)
    (type_Physical Eisenbahnwagen)
    (type_Rail_Route Paris_London_Rail_Route)
    (type_Rail_Route Stuttgart_Paris_Rail_Route)
    (type_Refrigerated Eisenbahnwagen)
    (type_Refrigerated_Tanker_Traincar Eisenbahnwagen)
    (type_Refrigerated_Vehicle Eisenbahnwagen)
    (type_Region BadenWuerttemberg)
    (type_Region LondonRegion)
    (type_Route Paris_London_Rail_Route)
    (type_Route Stuttgart_Paris_Rail_Route)
    (type_Speciality Eisenbahnwagen)
    (type_TCenter GareParisNord)
    (type_TCenter HauptbahnhofStuttgart)
    (type_TCenter LondonWaterloo)
    (type_Tanker Eisenbahnwagen)
    (type_Tanker_Vehicle Eisenbahnwagen)
    (type_Thing BadenWuerttemberg)
    (type_Thing Chemicalien)
    (type_Thing Eisenbahnwagen)
    (type_Thing GareParisNord)
    (type_Thing HauptbahnhofStuttgart)
    (type_Thing LokomotiveDB)
    (type_Thing LokomotiveSNCF)
    (type_Thing London)
    (type_Thing LondonRegion)
    (type_Thing LondonWaterloo)
    (type_Thing Paris)
    (type_Thing Paris_London_Rail_Route)
    (type_Thing Stuttgart)
    (type_Thing Stuttgart_Paris_Rail_Route)
    (type_Train LokomotiveDB)
    (type_Train LokomotiveSNCF)
    (type_Train_Station GareParisNord)
    (type_Train_Station HauptbahnhofStuttgart)
    (type_Train_Station LondonWaterloo)
    (type_Train_Station_Hub GareParisNord)
    (type_Traincar Eisenbahnwagen)
    (type_Vehicle Eisenbahnwagen)
    (type_Vehicle LokomotiveDB)
    (type_Vehicle LokomotiveSNCF)
    (type_Vehicle_Position BadenWuerttemberg)
    (type_Vehicle_Position Eisenbahnwagen)
    (type_Vehicle_Position GareParisNord)
    (type_Vehicle_Position HauptbahnhofStuttgart)
    (type_Vehicle_Position London)
    (type_Vehicle_Position LondonRegion)
    (type_Vehicle_Position LondonWaterloo)
    (type_Vehicle_Position Paris)
    (type_Vehicle_Position Stuttgart)
    (type_sort_for_BadenWuerttemberg BadenWuerttemberg)
    (type_sort_for_Chemicalien Chemicalien)
    (type_sort_for_Eisenbahnwagen Eisenbahnwagen)
    (type_sort_for_GareParisNord GareParisNord)
    (type_sort_for_HauptbahnhofStuttgart HauptbahnhofStuttgart)
    (type_sort_for_LokomotiveDB LokomotiveDB)
    (type_sort_for_LokomotiveSNCF LokomotiveSNCF)
    (type_sort_for_London London)
    (type_sort_for_LondonRegion LondonRegion)
    (type_sort_for_LondonWaterloo LondonWaterloo)
    (type_sort_for_Paris Paris)
    (type_sort_for_Paris_London_Rail_Route Paris_London_Rail_Route)
    (type_sort_for_Stuttgart Stuttgart)
    (type_sort_for_Stuttgart_Paris_Rail_Route Stuttgart_Paris_Rail_Route)
  )
  ((__top))
)
