(defproblem problem domain 
  (
    (In_City O27 Ulm)
    (In_City O28 Ulm)
    (At_Vehicle Pferd O27)
    (Connects James_Franck_Ring O27 O28)
    (Available James_Franck_Ring)
    (Available Pferd)
    (PV_Compatible Chemicalien Pferd)
    (RV_Compatible James_Franck_Ring Pferd)
    (At_Package Chemicalien O27)
    (type_Chemicals Chemicalien)
    (type_City Ulm)
    (type_City_Location O27)
    (type_City_Location O28)
    (type_Customer_Location O27)
    (type_Customer_Location O28)
    (type_Equipment_Position O27)
    (type_Equipment_Position O28)
    (type_Equipment_Position Pferd)
    (type_Equipment_Position Ulm)
    (type_Hazardous Chemicalien)
    (type_Liquid Chemicalien)
    (type_Local_Road_Route James_Franck_Ring)
    (type_Location O27)
    (type_Location O28)
    (type_Location Ulm)
    (type_Not_TCenter O27)
    (type_Not_TCenter O28)
    (type_Object Chemicalien)
    (type_Object Pferd)
    (type_Package Chemicalien)
    (type_Package_Storage_Position O27)
    (type_Package_Storage_Position O28)
    (type_Package_Storage_Position Pferd)
    (type_Package_Storage_Position Ulm)
    (type_Perishable Chemicalien)
    (type_Physical Chemicalien)
    (type_Physical Pferd)
    (type_Refrigerated Pferd)
    (type_Refrigerated_Tanker_Truck Pferd)
    (type_Refrigerated_Vehicle Pferd)
    (type_Road_Route James_Franck_Ring)
    (type_Route James_Franck_Ring)
    (type_Speciality Pferd)
    (type_Tanker Pferd)
    (type_Tanker_Vehicle Pferd)
    (type_Thing Chemicalien)
    (type_Thing James_Franck_Ring)
    (type_Thing O27)
    (type_Thing O28)
    (type_Thing Pferd)
    (type_Thing Ulm)
    (type_Truck Pferd)
    (type_Vehicle Pferd)
    (type_Vehicle_Position O27)
    (type_Vehicle_Position O28)
    (type_Vehicle_Position Ulm)
    (type_sort_for_Chemicalien Chemicalien)
    (type_sort_for_James_Franck_Ring James_Franck_Ring)
    (type_sort_for_O27 O27)
    (type_sort_for_O28 O28)
    (type_sort_for_Pferd Pferd)
    (type_sort_for_Ulm Ulm)
  )
  ((__top))
)
