(defproblem problem domain 
  (
    (In_City O27 Ulm)
    (In_City O28 Ulm)
    (In_City Bibliothek Ulm)
    (In_City Rathaus Ulm)
    (At_Vehicle Pferd Rathaus)
    (Connects James_Franck_Ring O27 O28)
    (Connects Frauen_Strasse Bibliothek O27)
    (Connects Albecker_Strasse Rathaus Bibliothek)
    (Available James_Franck_Ring)
    (Available Frauen_Strasse)
    (Available Albecker_Strasse)
    (Available Pferd)
    (PV_Compatible Toshiba_Laptops Pferd)
    (RV_Compatible James_Franck_Ring Pferd)
    (RV_Compatible Frauen_Strasse Pferd)
    (RV_Compatible Albecker_Strasse Pferd)
    (At_Package Toshiba_Laptops O27)
    (type_City Ulm)
    (type_City_Location Bibliothek)
    (type_City_Location O27)
    (type_City_Location O28)
    (type_City_Location Rathaus)
    (type_Customer_Location Bibliothek)
    (type_Customer_Location O27)
    (type_Customer_Location O28)
    (type_Customer_Location Rathaus)
    (type_Equipment_Position Bibliothek)
    (type_Equipment_Position O27)
    (type_Equipment_Position O28)
    (type_Equipment_Position Pferd)
    (type_Equipment_Position Rathaus)
    (type_Equipment_Position Ulm)
    (type_Local_Road_Route Albecker_Strasse)
    (type_Local_Road_Route Frauen_Strasse)
    (type_Local_Road_Route James_Franck_Ring)
    (type_Location Bibliothek)
    (type_Location O27)
    (type_Location O28)
    (type_Location Rathaus)
    (type_Location Ulm)
    (type_Not_TCenter Bibliothek)
    (type_Not_TCenter O27)
    (type_Not_TCenter O28)
    (type_Not_TCenter Rathaus)
    (type_Object Pferd)
    (type_Object Toshiba_Laptops)
    (type_Package Toshiba_Laptops)
    (type_Package_Storage_Position Bibliothek)
    (type_Package_Storage_Position O27)
    (type_Package_Storage_Position O28)
    (type_Package_Storage_Position Pferd)
    (type_Package_Storage_Position Rathaus)
    (type_Package_Storage_Position Ulm)
    (type_Parcels Toshiba_Laptops)
    (type_Physical Pferd)
    (type_Physical Toshiba_Laptops)
    (type_Regular Pferd)
    (type_Regular Toshiba_Laptops)
    (type_Regular_Truck Pferd)
    (type_Regular_Vehicle Pferd)
    (type_Road_Route Albecker_Strasse)
    (type_Road_Route Frauen_Strasse)
    (type_Road_Route James_Franck_Ring)
    (type_Route Albecker_Strasse)
    (type_Route Frauen_Strasse)
    (type_Route James_Franck_Ring)
    (type_Thing Albecker_Strasse)
    (type_Thing Bibliothek)
    (type_Thing Frauen_Strasse)
    (type_Thing James_Franck_Ring)
    (type_Thing O27)
    (type_Thing O28)
    (type_Thing Pferd)
    (type_Thing Rathaus)
    (type_Thing Toshiba_Laptops)
    (type_Thing Ulm)
    (type_Truck Pferd)
    (type_Vehicle Pferd)
    (type_Vehicle_Position Bibliothek)
    (type_Vehicle_Position O27)
    (type_Vehicle_Position O28)
    (type_Vehicle_Position Rathaus)
    (type_Vehicle_Position Ulm)
    (type_sort_for_Albecker_Strasse Albecker_Strasse)
    (type_sort_for_Bibliothek Bibliothek)
    (type_sort_for_Frauen_Strasse Frauen_Strasse)
    (type_sort_for_James_Franck_Ring James_Franck_Ring)
    (type_sort_for_O27 O27)
    (type_sort_for_O28 O28)
    (type_sort_for_Pferd Pferd)
    (type_sort_for_Rathaus Rathaus)
    (type_sort_for_Toshiba_Laptops Toshiba_Laptops)
    (type_sort_for_Ulm Ulm)
  )
  ((__top))
)
