(defproblem problem domain 
  (
    (In_City Firma Ulm)
    (In_City Universitaet Ulm)
    (At_Vehicle LKW Firma)
    (Connects James_Franck_Ring Firma Universitaet)
    (Available James_Franck_Ring)
    (Available LKW)
    (PV_Compatible Toshiba_Laptops LKW)
    (RV_Compatible James_Franck_Ring LKW)
    (At_Package Toshiba_Laptops Firma)
    (At_Vehicle Kuehlwagen Ulm)
    (Connects Landstrasse10 Ulm Heidenheim)
    (Available Landstrasse10)
    (Available Kuehlwagen)
    (PV_Compatible Tabletten Kuehlwagen)
    (RV_Compatible Landstrasse10 Kuehlwagen)
    (At_Package Tabletten Ulm)
    (type_Chemicals Tabletten)
    (type_City Heidenheim)
    (type_City Ulm)
    (type_City_Location Firma)
    (type_City_Location Universitaet)
    (type_Customer_Location Firma)
    (type_Customer_Location Universitaet)
    (type_Equipment_Position Firma)
    (type_Equipment_Position Heidenheim)
    (type_Equipment_Position Kuehlwagen)
    (type_Equipment_Position LKW)
    (type_Equipment_Position Ulm)
    (type_Equipment_Position Universitaet)
    (type_Hazardous Tabletten)
    (type_Liquid Tabletten)
    (type_Local_Road_Route James_Franck_Ring)
    (type_Location Firma)
    (type_Location Heidenheim)
    (type_Location Ulm)
    (type_Location Universitaet)
    (type_Not_TCenter Firma)
    (type_Not_TCenter Universitaet)
    (type_Object Kuehlwagen)
    (type_Object LKW)
    (type_Object Tabletten)
    (type_Object Toshiba_Laptops)
    (type_Package Tabletten)
    (type_Package Toshiba_Laptops)
    (type_Package_Storage_Position Firma)
    (type_Package_Storage_Position Heidenheim)
    (type_Package_Storage_Position Kuehlwagen)
    (type_Package_Storage_Position LKW)
    (type_Package_Storage_Position Ulm)
    (type_Package_Storage_Position Universitaet)
    (type_Parcels Toshiba_Laptops)
    (type_Perishable Tabletten)
    (type_Physical Kuehlwagen)
    (type_Physical LKW)
    (type_Physical Tabletten)
    (type_Physical Toshiba_Laptops)
    (type_Refrigerated Kuehlwagen)
    (type_Refrigerated_Tanker_Truck Kuehlwagen)
    (type_Refrigerated_Vehicle Kuehlwagen)
    (type_Regular LKW)
    (type_Regular Toshiba_Laptops)
    (type_Regular_Truck LKW)
    (type_Regular_Vehicle LKW)
    (type_Road_Route James_Franck_Ring)
    (type_Road_Route Landstrasse10)
    (type_Route James_Franck_Ring)
    (type_Route Landstrasse10)
    (type_Speciality Kuehlwagen)
    (type_Tanker Kuehlwagen)
    (type_Tanker_Vehicle Kuehlwagen)
    (type_Thing Firma)
    (type_Thing Heidenheim)
    (type_Thing James_Franck_Ring)
    (type_Thing Kuehlwagen)
    (type_Thing LKW)
    (type_Thing Landstrasse10)
    (type_Thing Tabletten)
    (type_Thing Toshiba_Laptops)
    (type_Thing Ulm)
    (type_Thing Universitaet)
    (type_Truck Kuehlwagen)
    (type_Truck LKW)
    (type_Vehicle Kuehlwagen)
    (type_Vehicle LKW)
    (type_Vehicle_Position Firma)
    (type_Vehicle_Position Heidenheim)
    (type_Vehicle_Position Ulm)
    (type_Vehicle_Position Universitaet)
    (type_sort_for_Firma Firma)
    (type_sort_for_Heidenheim Heidenheim)
    (type_sort_for_James_Franck_Ring James_Franck_Ring)
    (type_sort_for_Kuehlwagen Kuehlwagen)
    (type_sort_for_LKW LKW)
    (type_sort_for_Landstrasse10 Landstrasse10)
    (type_sort_for_Tabletten Tabletten)
    (type_sort_for_Toshiba_Laptops Toshiba_Laptops)
    (type_sort_for_Ulm Ulm)
    (type_sort_for_Universitaet Universitaet)
  )
  ((__top))
)
