(define
 (problem pfile_02_005)
 (:domain blocks)
 (:objects arm1 arm2 - ARM b1 b2 b3 b4 b5 - BLOCK)
 (:init
  (hand-empty arm1)
  (hand-empty arm2)
  (clear b4)
  (on-table b3)
  (on b4 b1)
  (on b1 b3)
  (clear b5)
  (on-table b2)
  (on b5 b2))
 (:goal (and
         (clear b3)
         (on-table b5)
         (on b3 b1)
         (on b1 b4)
         (on b4 b2)
         (on b2 b5)))
             (:tasks (task0 (achieve-goals arm1)))
             (:tasks (task1 (achieve-goals arm2)))
)